### ISSUE TITLE
Compiling BP

### ISSUE THREAD

**Issue by cheburashkalev** [BrUnOXaVIeRLeiTE/Unreal-Magic-Nodes#2]
[Magic Node]:  (C++) :: MGC String Array Sorting  unable to allocate Executable Function; Consider compiling or hot-reloading the C++ project before binding this node.

**Comment by BrUnOXaVIeRLeiTE** [comment]
You have to compile your node.
![mgc_guide](https://user-images.githubusercontent.com/7397894/138491739-21f300e5-bae7-4b85-95aa-55fa307fe6b5.png)

Click the "compile" button of the node then the Blueprint can link to the generated function.
