### ISSUE TITLE
Crash in AutoCompleteSuggestion

### ISSUE THREAD

**Issue by simulacrumgames** [BrUnOXaVIeRLeiTE/Unreal-Magic-Nodes#3]
I just downloaded the latest plugin from the marketplace and am going through your guide.

As soon as I start typing in the code area I crash at KMGC_TextEditorWidget:770 with an invalid memory access.

I believe the issue is here:
```
const FString &Script = GetPlainText().ToString();
Async(EAsyncExecution::TaskGraph,[this,&Keyword,&Script]() {
```

Correct me if I am wrong, but capturing the const reference `Script` by reference here is not safe.
I believe my system just so happens to be executing the lambda after `Script` has been destructed.

Here is a screen shot as well, you can see there is corrupted text for the first suggestion:
![image](https://user-images.githubusercontent.com/93084193/138597282-eab38c45-5ed9-460d-a01b-24a76b7ded37.png)

**Comment by BrUnOXaVIeRLeiTE** [comment]
Will take a look when possible. Thanks for reporting.

**Comment by BrUnOXaVIeRLeiTE** [comment]
The fix will be sent to the marketplace repo later, when Epic have to time to update the pack.

**Comment by simulacrumgames** [comment]
Thank you for the quick response, I will verify it and close the ticket as soon as I can.

**Comment by simulacrumgames** [comment]
I saw an update come through but the code isn't any different.

This is the version in .uplugin:

"VersionName": "0.4.6"

Any idea what I'm doing wrong?

**Comment by BrUnOXaVIeRLeiTE** [comment]
Epic uploaded patch for UE4.27 for now.

**Comment by simulacrumgames** [comment]
Do you have any idea how long it usually takes for the update to go through?

Thank you.

**Comment by BrUnOXaVIeRLeiTE** [comment]
They have already published update for Unreal 4.26 and 4.27.

I can't update versions older than that.

**Comment by simulacrumgames** [comment]
Oh, I'm using 4.27 but the included code doesn't have the change you made.

I removed the plugin and re-installed it and it still has the same old code.

Is this the correct info for the uplugin file?
	"FileVersion": 3,
	"Version": 1,
	"VersionName": "0.4.6",

I tried making the change myself but it doesn't seem like the library is actually being recompiled so I'm not sure what to do...

**Comment by BrUnOXaVIeRLeiTE** [comment]
That's not the updated version.

You can find updated source here :
[https://www.dropbox.com/s/pgjmrx14db1hk65/MagicNode_0.4.7_UE4.27.zip?dl=0](https://www.dropbox.com/s/pgjmrx14db1hk65/MagicNode_0.4.7_UE4.27.zip?dl=0)

**Comment by simulacrumgames** [comment]
Ok I put this in my project and built, then copied to the engine directory and it works.

Not sure why when I download from marketplace it has the wrong version.
