### ISSUE TITLE
Current "5" version auto-complete visual bug, search for types never finishes

### ISSUE THREAD

**Issue by Nocxr** [BrUnOXaVIeRLeiTE/Unreal-Magic-Nodes#4]
Hey this is sort of a 2 issue post, I was not sure if they were related or not but I didn't want to open 2 issues if they were: 

While using either the launcher to install magic nodes to 5.0.1 or using the github code on commit (23ab872541cce1f8ed7986ab7a5f4fed9078caa4) when attempting to use the magic node the auto-complete/suggestion windows are all white as shown below:
![UnrealEditor_OtYgovKpJF](https://user-images.githubusercontent.com/72276215/165408122-80fd4ee2-2c7e-4139-bed0-5975a40a90a3.gif)

It seems it is indeed working, you just cant read anything its showing?  I have tried reinstalling the engine as well as disabling any non standard plugins and the issue persists.  I can confirm installing the plugin to 4.27.2 works/displays as expected.

The second issue is the auto-complete system search for types button will start and seemingly never end on 5.0.1, I have run it on 4.27.2 and confirmed it takes about 3-5 (running on a 5900x) minutes to finish successfully.  On 5.0.1 I have started it and left it running for over an hour and it still shows the bar moving at the bottom, it also has a process/thread that continues to run in the background even after the engine is closed and wont stop until manually ended.

If either of these issues are something on my end I apologize I just wanted to reach out and see if there was anything I could do in the mean time to start working with these nodes.  I just found your plugin recently and was very excited to start messing with it, please let me know if there is any other information or tests I could run that might provide helpful, thanks!

**Comment by BrUnOXaVIeRLeiTE** [comment]
Seems like Epic made (again) changes to Editor styles.
The styles used should not be "white". I will take a look once I finish some work tasks.

The db search, I have to investigate.
Thank you for reporting.

**Comment by BrUnOXaVIeRLeiTE** [comment]
Fixed on Unreal 5.0.2:

![MGC](https://user-images.githubusercontent.com/7397894/172102971-46b6c509-baa6-4ea7-b0fc-9c9538b7e9fd.png)

**Comment by BrUnOXaVIeRLeiTE** [comment]
The problem about very long search for classes, well.
Unreal 5 is just very VERY big. So the search for classes goes on and on.

Just the Python API adds over 15GB of code.
So I have added a timeout for the type scan process, but it's still working as before.
